# Generated by Django 3.0.5 on 2020-05-07 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Palace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PathType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('palace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='streetmarkers.Palace')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='streetmarkers.PathType')),
            ],
        ),
        migrations.CreateModel(
            name='PalaceOwners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('palace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streetmarkers.Palace')),
            ],
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('infoText', models.TextField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('path', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='streetmarkers.Path')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='streetmarkers.MarkerType')),
            ],
        ),
    ]
