# Generated by Django 3.0.5 on 2020-05-07 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streetmarkers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel("PalaceOwners", "PalaceOwner")
    ]
