# Generated by Django 3.0.5 on 2020-04-29 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetmarkers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='infoText',
            field=models.TextField(),
        ),
    ]
