# Generated by Django 3.0.5 on 2020-05-08 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streetmarkers', '0003_auto_20200508_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemarker',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basemarker',
            name='palace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='streetmarkers.Palace'),
        ),
        migrations.AddField(
            model_name='path',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
