# Generated by Django 3.0.5 on 2020-05-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetmarkers', '0004_auto_20200508_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemarker',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
