# Generated by Django 3.0.5 on 2020-05-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peg',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
