# Generated by Django 3.0.5 on 2020-05-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegs', '0002_peg_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peg',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
