# Generated by Django 3.0.5 on 2020-05-14 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pegs', '0003_auto_20200513_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegsystem',
            name='pegType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pegs.PegType'),
        ),
    ]
